spring:
  application:
    name: florist

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com

elasticpathcloud:
  pcm:
    baseUrl: https://useast.api.elasticpath.com/pcm
    authUrl: https://useast.api.elasticpath.com
    clientId: eYSp7n5pTQ1uD8E253ooicnr5tMpd4BxHvFp8Di8Wu
    clientSecret: 3mwE2NCtsn8vpKOOVU1y1i5CvFzDCbEcXxrerQ1vL6
    getHierarchies.path: /hierarchies
    getHierarchyChildNodes.path: /hierarchies/{hierarchyId}/children
    getProducts.path: /products
    getNodeProducts.path: /hierarchies/{hierarchyId}/nodes/{nodeId}/products
    getVariations.path: /variations
    getClientCredentials.path: /oauth/access_token
  accounts:
    baseUrl: https://useast.api.elasticpath.com
    createAccount.path: /v2/accounts
    getAccount.path: /v2/accounts/{accountID}
    getAccounts.path: /v2/accounts
    generateAccountManagementAuthorizationToken.path: v2/account-members/tokens
    getAccountAuthenticationSettings.path: /v2/settings/account-authentication
    getAccountAuthenticationRealmOidcProfiles.path: /v2/authentication-realms/{authenticationRealmId}/oidc-profiles
    getAccountAuthenticationRealmPasswordProfiles.path: /v2/authentication-realms/{authenticationRealmId}/password-profiles
    createUserAuthenticationInfo.path: /v2/authentication-realms/{authenticationRealmId}/user-authentication-info
    createUserAuthenticationPasswordProfile.path:  /v2/authentication-realms/{authenticationRealmId}/user-authentication-info/{userAuthenticationInfoId}/user-authentication-password-profile-info
    createOneTimePasswordToken.path : /v2/authentication-realms/{authenticationRealmId}/password-profiles/{passwordProfileId}/one-time-password-token-request
  carts:
    createCustomCart.path: /v2/carts
    createAccountCartAssociation.path: v2/carts/{cartId}/relationships/accounts
    createBulkAddItemsToCart.path: /v2/carts/{cartId}/items
    checkoutPath.path: /v2/carts/{cartId}/checkout
  data:
    mongodb:
      uri: mongodb://localhost:27017/florist